### ISSUE TITLE
ハンドヘルド側でソケットを閉じたときにサーバーが落ちる

### ISSUE THREAD

**Issue by prprhyt** [JAG-SC/ABC2016SpringServer#17]
タイトルの通りです。ハンドヘルド側で再接続処理を書きましたが上記理由により動作確認が取れず。

**Comment by NewNotMoon** [comment]
落ちるとはどういう状況なのか説明してください。何かエラーを吐くのか、黙って終了するのか。サーバーのビルドソースコードが最新になっているかも書いてください。

**Comment by NewNotMoon** [comment]
少なくとも私の手元ではアプリを再起動しても正常に動作しますし、ソケットが閉じられたことが原因なのかすらも不明確です。
**どういうコードを書いたら問題が発生したのか、どういう問題が起きるのか、**詳しく書かないとIssueを立てても何の問題解決にもなりませんよ

**Comment by NewNotMoon** [comment]
とりあえず、こちらで修正を入れたので、問題が解決するか確認して下さい。

**Comment by prprhyt** [comment]
問題解決しました。ハンドヘルドとの再接続も正常に動作しました。
